name: frontend
description: "A well-structured, functional, and up-to-date Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  socket_io_common: ^2.0.3
  google_fonts: ^6.2.1
  path_provider: ^2.1.4
  font_awesome_flutter: ^10.7.0
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/images/

lib:
  - lib/
  - lib/l10n/arb/
